### ISSUE TITLE
Using the client within Sinatra

### ISSUE THREAD

**Issue by timschwab** [imanel/websocket-eventmachine-client#15]
I am writing code for a Sinatra web server that needs to receive a request from a client, then establish a connection to another server whose API only accepts WebSockets, process the information sent through the WebSocket, then send back a response to the client who initially made the request.

I believe I can do this with a combination of your gem and the [async_sinatra](https://github.com/raggi/async_sinatra) extension to Sinatra. async_sinatra uses Eventmachine, so theoretically it should be able to hook up quite nicely. But I am rather new to the whole Ruby environment, so I don't really know what I'm doing.

My code looks something like this at the moment:

```
require 'sinatra'
require 'sinatra/async'
require 'websocket-eventmachine-client'

register Sinatra::Async

apost 'route' do
  ws = WebSocket::EventMachine::Client.connect(:uri => 'wss://example.com')
  puts 'connecting...'

  ws.onopen do
    puts 'WS open'
    ws.send 'A message'
  end

  ws.onmessage do
    # stuff
  end

  ws.onclose do
    body 'Response to client'
  end

end
```

I do not wrap it in `EM.run` because I believe that async_sinatra already wraps the entire method in that already. `EM.reactor_running?` returns true. When I run this and hit the route with Postman, "connecting..." gets logged but nothing else, and Postman never gets a response. I am certain that the problem is not on the other server's end. Do you have any suggestions?

**Comment by imanel** [comment]
Do you receive information where should you connect to via HTTP request, or is it always the same? If later is true then connecting before request might be good idea, otherwise if server will send anything before client is connected it might get lost.

`onmessage` receives message [as block parameter](https://github.com/imanel/websocket-eventmachine-client#onmessage). Are you logging what is sent to it to see if for sure data were transfered?

`onclose` need to be called either by server, or you manually. Since WS is usually designed to last long I'm not sure if other end is doing it immediately after sending data (if you will share documentation of endpoint that you are using I might offer better help), so it might never happen waiting for more messages.
