### ISSUE TITLE
Is there a way to handle code 1009

### ISSUE THREAD

**Issue by bonafernando** [imanel/websocket-eventmachine-client#20]
Is there a way to increase frame_size?

**Comment by imanel** [comment]
TBH I never prepared code to actually using frame sizes, as protocol states that frame size should be up to 2^63 bytes (which is slightly above 9 exabytes), however there is not documented way of doing so manually. When you're [sending message](https://github.com/imanel/websocket-eventmachine-base/blob/master/lib/websocket/eventmachine/base.rb#L60-L76) you can provide [continuation type](https://github.com/imanel/websocket-ruby/blob/master/lib/websocket/frame/handler/handler07.rb#L10). This will allow you to split frame the way you want. Let me know if that solves your issue, otherwise we could discuss what exactly is your use case and how I could add support for it.

**Comment by bonafernando** [comment]
Hi there. My bad, this error was a server error. I was sending a request of too much information at once and the server wasn't able to handle it. I splat the request by half on `onopen` and the other half on a `EventMachine.add_timer(10)`. Thanks.
